#!/bin/sh

if [ -f Makefile ]; then
    make clean
fi
find . -name 'CMakeFiles' -type d -exec rm -rf {} \;
find . -name 'CMakeCache.txt' -type f -exec rm -rf {} \;
find . -name 'cmake_install.cmake' -type f -exec rm -rf {} \;
find . -name 'Makefile' -type f -exec rm -rf {} \;
